name: cpm-hub
description: CPM Hub open source server for hosting CPM software
packages:
    api:
        cflags: [-std=c++11, -g]
    domain:
        cflags: [-std=c++11, -g]
    infrastructure:
        cflags: [-std=c++11, -g]
plugins:
    cest: "1.0"
    mongoose: "6.16"
    json: "3.7.3"
    fakeit: "2.0.5"
    base64: "1.0"
    inih: "1.0"
link_options:
    libraries: ['boost_filesystem', 'boost_system', 'boost_program_options', 'pthread', 'ssl', 'crypto']
