project_name: cpm-hub
description: CPM Hub open source server for hosting CPM software
packages:
    api:
        cflags:
            - -std=c++11
    domain:
    infrastructure:
plugins:
    cest: "1.0"
    mongoose: "6.16"
    json: "3.7.3"
    fakeit: "2.0.5"
