name: 'cpm-hub'
description: 'CPM Hub open source server for hosting CPM bits'
build:
  packages:
    cpm-hub/http:
    cpm-hub/infrastructure:
    cpm-hub/management:
    cpm-hub/bits:
    cpm-hub/templates:
    cpm-hub/users:
    cpm-hub/authentication:
    cpm-hub/logging:
    cpm-hub/kpi:
    cpm-hub/database:
  bits:
    mongoose: '6.16'
    json: '3.7.3'
    base64: '1.0'
    blake3: '1.0'
    inih: '1.0'
    spdlog:
      version: '1.6.1'
      cppflags: ['-DSPDLOG_COMPILED_LIB']
    sqlite3: '3.32.3'
  libraries: [ 'boost_filesystem', 'boost_system', 'boost_program_options', 'pthread', 'ssl', 'crypto' ]
test:
  packages:
    tests/mocks:
  bits:
    fakeit: '2.0.5'
    cest: '1.0'
    cpputest: 'latest'
targets:
  default:
    main: 'main.cpp'
    build:
      cppflags: [ '-std=c++11', '-g' ]
  ubuntu.20.04:
    main: 'main.cpp'
    dockerfile: 'ubuntu.20.04.Dockerfile'
    build:
      cppflags: ['-std=c++11', '-g', '-O2']
