name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        pip3 install cpm-cli
        pip3 install pyyaml
        sudo apt install -yq ninja-build g++ libboost-all-dev
    - name: Test with CPM
      run: |
        cpm test
    - name: Build
      run: |
        cpm build
