name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
        matrix:
          python-version: [ 3.7 ]

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        pip3 install cpm-cli
    - name: Test with CPM
      run: |
        cpm test
