name: C/C++ CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          pip3 install --upgrade cpm-cli
          pip3 install pyyaml
          pip3 install requests
          sudo apt install -yq ninja-build g++ libboost-all-dev cpputest
          cpm install
      - name: Test with CPM
        run: |
          cpm test
      - name: Build
        run: |
          cpm build
      - uses: actions/upload-artifact@v1
        with:
          name: cpm-hub
          path: build/cpm-hub
